### ISSUE TITLE
Cant find comand 'SegmentBoneFromCT '

### ISSUE THREAD

**Issue by NotF404** [rg2/xreg#24]
hi @rg2 

Thanks for your gorgeous work. 
I cant find comand `SegmentBoneFromCT ` when  getting through the Walkthrough below
https://github.com/rg2/xreg/wiki/Walkthrough%3A-Bone-Segmentation

How to install SegmentBoneFromCT?

**Comment by rg2** [comment]
Hi @NotF404 , thanks for your question.

You can try using a pre-compiled version from here: https://github.com/rg2/bone-segmentation/releases

If those do not work, then you can try compiling directly from the source code: https://github.com/mkrcah/bone-segmentation

**Comment by NotF404** [comment]
That is helpful for me, Thanks again.
