### ISSUE TITLE
Single object multi-view registration

### ISSUE THREAD

**Issue by SJTUdemon** [rg2/xreg#27]
1. How to create multiple dicom fluoroscopy and their corresponding .fcsv files into an h5 file?
2. How to register a single object, multiple views?

**Comment by rflepp** [comment]
Are there any updates to this question?

**Comment by rg2** [comment]
You can adapt these examples and the linked code for annotating fcsv and adding to h5
- https://github.com/rg2/xreg/wiki/Example%3A-TCIA-Hip-Radiograph-Rigid-Registration
- https://github.com/rg2/xreg/wiki/Example%3A-C-arm-orbital-rotation-axis

The second example also shows how to combine multiple single-view h5 projection data files into a single multi-view file with updated extrinsics.

This example and code can be adapted to register a single object in multiple views:
- https://github.com/rg2/xreg/wiki/Walkthrough%3A-Multiple-View-PAO-Fragment-Registration
